### ISSUE TITLE
Examples available?

### ISSUE THREAD

**Issue by bcmdev** [foo123/serialiser.js#1]
Hello Nikos,

i found your script on stackoverflow and was wondering if you have an example on how to use it? I'm looking for a way to get form data into an object and back. 

Thanks in advance!

**Comment by foo123** [comment]
yes sure here is one (an actual working example from a running site, bit modified):

Assuming you have a form with fields whose key is the name attribute and value is the value attribute and you can structure it and style it anyway you want.

`Seialiser` will read the data from the form by key/value (taking into account multiple fields, ie array fields with same key) and will construct a data object. Then this data object can be typecast selectively for example in order to cobvert some values to numbers or whatever is needed and then optionaly and selectively some values can be validated using a plethora of validator methods (or custom ones) and functional validator expressions (eg AND, OR, ..)

In a sense this lib is a scaled down or light-weight version of modelview-form.js which a full-scale MVC form framework with typecasters and validators, for some less complex projects.

```javascript
var get_key = Serialiser.Key( 'name' ),
get_value = Serialiser.Value( 'value' ),
        types = {
         id                     : Serialiser.Type.INT
        ,user                   : Serialiser.Type.INT
        ,title                  : Serialiser.Type.STR
        ,type                   : [Serialiser.Type.INT] // multipl;e fields
        ,name                 : [Serialiser.Type.STR] // multiple fields
        },
        validators = {
         title                  : [Serialiser.Validator.REQUIRED, 'Field is required'] // array of validator, error message
        ,start                  : [Serialiser.Validator.EXPRESSION('"independent" === model.type'),'Type should be "independent"']
        ,start_times   : [[Serialiser.Validator.REQUIRED, 'Field is required']] // multiple fields, array of array
        }
;

    $form.on('submit', function( evt ){
        evt.preventDefault( );
        evt.stopPropagation( );
        var form_fields = $form.find( 'input[name],textarea[name],select[name]' ),
            err_msgs = $form.find( '[data-form-error]' ),
            err, data = { };
        
        // model fields
        Serialiser.FieldsToModel( form_fields.toArray(), data, get_key, get_value );
        data = Serialiser.Typecast( data, types ); // in case you want to typecast the field values
        if ( !Serialiser.Validate( data, validators, err={} ) )
        {
            notify('Please fix errors first!');
        }
        else
        {
            $.post(ajaxurl, data);
        }
        return false;
    });

````

Maybe i should add a couple of examples but if one checks the codebase, it should (hopefuly) be clear how to use. This is because i use most of what is posted on github for me personaly and work i do, but also have it in case others may find them useful (as i myself have done for others)

**Comment by bcmdev** [comment]
Hello Nikos, thanks a lot for your quick feedback. Will try this!

**Comment by foo123** [comment]
Note that although the lib can serialise complex and nested key/values of a form (including uploaded files) into a model object eg:

```javascript
{
key:{
  key1: {
      // for example a form field with name="key.key1.key2" value="value"
      key2: value
}
}
}
```

The typecasters and validators take into account ONLY first level keys. It is easy to make them nested, but the original purpose was to handle arbitrary arrays of key/values where the index is not known before-hand, ie dynamicaly added and deleted form fields. And this makes nested key types and validators awkward, since the index would be variable. One can always roll a custom typecaster and/or validator for the needs at hand to handle nested lists of keys/values, but one is not provided by default right now.

**Comment by bcmdev** [comment]
Ok, thanks!
